"""ORION dependency network: 67 links forming real predecessor chains.

Tuple order:
  ref, name, type, upstream, upstreamOwner, downstream, downstreamOwner,
  dueOffset, status, criticality, delayProbability, potentialDelayDays,
  affectedMilestones, affectedBenefits, predecessors
"""

from orion_core import day

DEPENDENCIES = [
    # --- Scenario A: vendor delay to customer launch ------------------------
    ("DEP-01", "Carrier API specification v2.1 from TMS vendor", "vendor",
     "Nordwind Systems (TMS vendor)", "own-14", "Integration and Data Platform", "own-06",
     300, "late", "critical", 0.95, 21, ["ms-13"], ["ben-04"], []),
    ("DEP-02", "Tier 1 carrier API certification slots", "external",
     "Tier 1 carrier IT teams", "own-07", "Carrier API integration", "own-06",
     332, "at-risk", "critical", 0.7, 14, ["ms-13", "ms-17"], ["ben-04", "ben-02"], ["DEP-01"]),
    ("DEP-03", "Hardened security test environment", "internal",
     "Group Security Engineering", "own-13", "Security testing", "own-13",
     352, "at-risk", "critical", 0.6, 12, ["ms-14"], ["ben-04"], ["DEP-02"]),
    ("DEP-04", "Penetration test vendor engagement window", "vendor",
     "Aegis Assurance", "own-13", "Security testing sign-off", "own-13",
     368, "at-risk", "critical", 0.5, 10, ["ms-14"], ["ben-04"], ["DEP-03"]),
    ("DEP-05", "Production cutover change freeze approval", "internal",
     "Group IT Change Board", "own-02", "TMS go-live wave 1", "own-05",
     392, "at-risk", "critical", 0.45, 9, ["ms-10"], ["ben-04", "ben-09"], ["DEP-04"]),
    ("DEP-06", "Customer communication and launch approval", "internal",
     "Commercial and Marketing", "own-01", "Customer launch", "own-01",
     412, "on-track", "high", 0.3, 7, ["ms-32"], ["ben-04"], ["DEP-05"]),

    # --- Scenario B: data quality to reporting to scope change -------------
    ("DEP-07", "Master data steward capacity from regional operations", "internal",
     "Regional operations data stewards", "own-12", "Data quality remediation", "own-12",
     296, "late", "critical", 0.9, 24, ["ms-15"], ["ben-05"], []),
    ("DEP-08", "Reference data from legacy TMS extracts", "internal",
     "Legacy TMS support team", "own-12", "Data migration", "own-06",
     262, "delivered", "high", 0.1, 5, ["ms-12", "ms-15"], [], []),
    ("DEP-09", "Certified data set for reporting suite", "internal",
     "Data Quality", "own-12", "Reporting suite v1", "own-09",
     326, "at-risk", "critical", 0.75, 18, ["ms-26"], ["ben-08"], ["DEP-07"]),
    ("DEP-10", "Finance reconciliation sign-off on reporting", "internal",
     "Group Finance", "own-11", "Reporting suite v1", "own-09",
     340, "at-risk", "high", 0.55, 12, ["ms-26", "ms-20"], ["ben-08"], ["DEP-09"]),

    # --- Scenario C: supplier capacity to revenue benefit -------------------
    ("DEP-11", "Automation supplier build slot, Milan line", "vendor",
     "Meridian Intralogistics", "own-14", "Milan automation install", "own-08",
     318, "late", "critical", 0.92, 28, ["ms-22"], ["ben-03"], []),
    ("DEP-12", "Milan hub power upgrade by utility", "external",
     "Enel distribution", "own-04", "Milan automation install", "own-08",
     306, "at-risk", "critical", 0.6, 20, ["ms-22", "ms-04"], ["ben-03"], []),
    ("DEP-13", "Installation crew mobilisation", "vendor",
     "Meridian Intralogistics", "own-14", "Milan automation install", "own-08",
     344, "at-risk", "critical", 0.7, 16, ["ms-22"], ["ben-03"], ["DEP-11", "DEP-12"]),
    ("DEP-14", "FAT commissioning engineers", "vendor",
     "Meridian Intralogistics", "own-14", "Automation commissioning", "own-08",
     376, "at-risk", "critical", 0.65, 14, ["ms-23"], ["ben-03", "ben-08"], ["DEP-13"]),
    ("DEP-15", "Warehouse operatives recruited and trained", "internal",
     "Milan hub HR", "own-15", "Warehouse go-live wave 1", "own-08",
     388, "at-risk", "high", 0.5, 11, ["ms-24"], ["ben-03", "ben-06"], ["DEP-14"]),

    # --- Network workstream ------------------------------------------------
    ("DEP-16", "Board investment approval for hub consolidation", "internal",
     "Investment Committee", "own-01", "Network Design", "own-04",
     88, "delivered", "critical", 0.05, 10, ["ms-02"], ["ben-01"], []),
    ("DEP-17", "Frankfurt landlord lease negotiation", "external",
     "Rheinpark Logistik GmbH", "own-04", "Frankfurt hub lease", "own-04",
     160, "delivered", "high", 0.1, 14, ["ms-03"], ["ben-01"], ["DEP-16"]),
    ("DEP-18", "Milan hub building permit", "regulatory",
     "Comune di Milano", "own-04", "Milan hub fit-out", "own-04",
     252, "delivered", "critical", 0.1, 30, ["ms-04"], ["ben-01"], ["DEP-16"]),
    ("DEP-19", "Racking and MHE delivery, Milan", "vendor",
     "Stella Storage Systems", "own-14", "Milan hub fit-out", "own-04",
     292, "at-risk", "high", 0.4, 12, ["ms-04"], ["ben-01"], ["DEP-18"]),
    ("DEP-20", "Works council consultation, Italy", "regulatory",
     "Italian works council", "own-10", "Network cutover wave 1", "own-04",
     360, "at-risk", "high", 0.45, 21, ["ms-05"], ["ben-01"], []),
    ("DEP-21", "Legacy site exit notices served", "internal",
     "Property and Facilities", "own-04", "Network cutover wave 1", "own-04",
     380, "on-track", "medium", 0.25, 10, ["ms-05"], ["ben-01"], ["DEP-20"]),
    ("DEP-22", "Transport plan re-baselined for seven hubs", "internal",
     "Network Design", "own-04", "TMS configuration build", "own-05",
     284, "delivered", "high", 0.15, 8, ["ms-08"], ["ben-01"], ["DEP-16"]),

    # --- TMS workstream ----------------------------------------------------
    ("DEP-23", "TMS vendor contract execution", "vendor",
     "Nordwind Systems", "own-14", "TMS Delivery", "own-05",
     78, "delivered", "critical", 0.05, 12, ["ms-06"], ["ben-09"], []),
    ("DEP-24", "Design authority review slot", "internal",
     "Enterprise Architecture", "own-06", "TMS design sign-off", "own-05",
     146, "delivered", "high", 0.1, 7, ["ms-07"], [], ["DEP-23"]),
    ("DEP-25", "TMS non-production environments", "vendor",
     "Nordwind Systems", "own-14", "TMS configuration build", "own-05",
     212, "delivered", "critical", 0.1, 15, ["ms-08"], [], ["DEP-23"]),
    ("DEP-26", "Business rules confirmed by operations", "internal",
     "Hub operations managers", "own-15", "TMS configuration build", "own-05",
     276, "at-risk", "high", 0.4, 10, ["ms-08"], ["ben-01"], []),
    ("DEP-27", "UAT business tester availability", "internal",
     "Regional operations", "own-15", "TMS UAT exit", "own-05",
     342, "at-risk", "critical", 0.6, 15, ["ms-09"], ["ben-04"], ["DEP-26"]),
    ("DEP-28", "Defect fix releases from TMS vendor", "vendor",
     "Nordwind Systems", "own-14", "TMS UAT exit", "own-05",
     356, "at-risk", "critical", 0.55, 12, ["ms-09"], ["ben-04"], ["DEP-27"]),
    ("DEP-29", "Hypercare support contract in force", "vendor",
     "Nordwind Systems", "own-14", "TMS go-live wave 1", "own-05",
     386, "on-track", "high", 0.25, 8, ["ms-10"], ["ben-09"], ["DEP-23"]),
    ("DEP-30", "Legacy TMS decommission approval", "internal",
     "Group IT Asset Management", "own-05", "Legacy decommission", "own-05",
     408, "on-track", "medium", 0.3, 14, ["ms-28"], ["ben-09"], ["DEP-29"]),

    # --- Integration and data ----------------------------------------------
    ("DEP-31", "API gateway capacity uplift", "internal",
     "Group Platform Engineering", "own-06", "Integration platform", "own-06",
     268, "delivered", "high", 0.15, 10, ["ms-13"], [], []),
    ("DEP-32", "Event backbone licence extension", "vendor",
     "Streamline Data", "own-14", "Integration platform", "own-06",
     288, "delivered", "medium", 0.2, 9, ["ms-13", "ms-25"], [], []),
    ("DEP-33", "Canonical data model ratified", "internal",
     "Enterprise Architecture", "own-06", "Data migration", "own-06",
     232, "delivered", "high", 0.1, 8, ["ms-11", "ms-12"], [], []),
    ("DEP-34", "Data quality tooling licences", "vendor",
     "Veridian Data Quality", "own-14", "Data quality remediation", "own-12",
     272, "delivered", "medium", 0.2, 7, ["ms-15"], ["ben-05"], []),
    ("DEP-35", "Threat model review by security architecture", "internal",
     "Security Architecture", "own-13", "Security testing", "own-13",
     338, "at-risk", "high", 0.5, 10, ["ms-14"], [], ["DEP-31"]),
    ("DEP-36", "Data protection impact assessment approval", "regulatory",
     "Group Data Protection Office", "own-13", "Carrier API integration", "own-06",
     324, "at-risk", "high", 0.4, 14, ["ms-13", "ms-19"], ["ben-07"], []),
    ("DEP-37", "Migration cutover data freeze", "internal",
     "Regional operations", "own-12", "TMS go-live wave 1", "own-05",
     390, "on-track", "high", 0.3, 6, ["ms-10", "ms-15"], [], ["DEP-07"]),
    ("DEP-38", "Predictive ETA feature store", "internal",
     "Group Data Science Platform", "own-09", "Predictive ETA model", "own-09",
     372, "on-track", "medium", 0.35, 12, ["ms-27"], ["ben-08"], ["DEP-32"]),

    # --- Carrier and compliance --------------------------------------------
    ("DEP-39", "Carrier framework agreement templates from legal", "internal",
     "Group Legal", "own-07", "Carrier onboarding", "own-07",
     150, "delivered", "high", 0.1, 12, ["ms-16"], ["ben-02"], []),
    ("DEP-40", "Insurance certificate verification service", "vendor",
     "CertifyEU", "own-07", "Carrier onboarding", "own-07",
     288, "delivered", "medium", 0.2, 8, ["ms-17"], ["ben-07"], ["DEP-39"]),
    ("DEP-41", "Tier 1 carrier contract counter-signature", "external",
     "Tier 1 carriers", "own-07", "Tier 1 onboarding", "own-07",
     312, "at-risk", "high", 0.45, 16, ["ms-17"], ["ben-02"], ["DEP-39"]),
    ("DEP-42", "Tier 2 carrier tender award", "internal",
     "Procurement", "own-07", "Tier 2 onboarding", "own-07",
     350, "on-track", "medium", 0.3, 14, ["ms-18"], ["ben-02"], ["DEP-41"]),
    ("DEP-43", "Customs broker system interface specification", "external",
     "Hanseatic Customs Services", "own-07", "Customs broker integration", "own-07",
     318, "late", "critical", 0.85, 18, ["ms-19"], ["ben-07"], ["DEP-36"]),
    ("DEP-44", "EU customs authority test account", "regulatory",
     "National customs authorities", "own-07", "Customs broker integration", "own-07",
     336, "at-risk", "high", 0.5, 20, ["ms-19"], ["ben-07"], ["DEP-43"]),
    ("DEP-45", "Carrier performance data feed", "internal",
     "Control Tower", "own-09", "Carrier scorecard", "own-07",
     384, "on-track", "medium", 0.3, 9, ["ms-20"], ["ben-02"], ["DEP-09"]),
    ("DEP-46", "Carrier onboarding portal enhancements", "internal",
     "Group Digital", "own-07", "Tier 2 onboarding", "own-07",
     344, "on-track", "low", 0.25, 7, ["ms-18"], ["ben-02"], ["DEP-40"]),

    # --- Warehouse automation ----------------------------------------------
    ("DEP-47", "Automation contract award", "internal",
     "Procurement", "own-14", "Warehouse Automation", "own-08",
     126, "delivered", "critical", 0.05, 15, ["ms-21"], ["ben-03"], ["DEP-16"]),
    ("DEP-48", "Milan floor slab load certification", "external",
     "Structural engineering consultancy", "own-04", "Milan automation install", "own-08",
     300, "delivered", "high", 0.15, 12, ["ms-22"], ["ben-03"], ["DEP-18"]),
    ("DEP-49", "Automation control software release", "vendor",
     "Meridian Intralogistics", "own-14", "Automation commissioning", "own-08",
     366, "at-risk", "critical", 0.6, 15, ["ms-23"], ["ben-03"], ["DEP-11"]),
    ("DEP-50", "WMS to automation interface build", "internal",
     "Integration and Data Platform", "own-06", "Automation commissioning", "own-08",
     362, "at-risk", "critical", 0.55, 13, ["ms-23"], ["ben-03"], ["DEP-31"]),
    ("DEP-51", "Health and safety certification, Milan automation", "regulatory",
     "Italian workplace safety authority", "own-08", "Warehouse go-live wave 1", "own-08",
     396, "on-track", "high", 0.35, 18, ["ms-24"], ["ben-03", "ben-06"], ["DEP-14"]),
    ("DEP-52", "Frankfurt automation design freeze", "internal",
     "Warehouse Automation", "own-08", "Network cutover wave 1", "own-04",
     370, "on-track", "medium", 0.3, 10, ["ms-05"], ["ben-01"], ["DEP-47"]),

    # --- Control tower and analytics ---------------------------------------
    ("DEP-53", "Control tower cloud tenancy provisioned", "internal",
     "Group Cloud Platform", "own-09", "Control tower MVP", "own-09",
     258, "delivered", "high", 0.1, 8, ["ms-25"], [], []),
    ("DEP-54", "Visibility data sharing agreements with carriers", "external",
     "Tier 1 carriers", "own-07", "Control tower MVP", "own-09",
     282, "at-risk", "high", 0.4, 12, ["ms-25", "ms-28"], ["ben-08"], ["DEP-41"]),
    ("DEP-55", "Reporting tool licences for run organisation", "vendor",
     "Lumen Analytics", "own-09", "Reporting suite v1", "own-09",
     330, "on-track", "medium", 0.25, 7, ["ms-26"], ["ben-08"], []),
    ("DEP-56", "Model risk review for predictive ETA", "internal",
     "Group Model Risk", "own-13", "Predictive ETA model", "own-09",
     380, "on-track", "medium", 0.35, 14, ["ms-27"], ["ben-08"], ["DEP-38"]),
    ("DEP-57", "Control tower operating model sign-off", "internal",
     "Operations leadership", "own-15", "Control tower full rollout", "own-09",
     398, "on-track", "high", 0.3, 12, ["ms-28"], ["ben-08"], ["DEP-55"]),
    ("DEP-58", "Exception taxonomy agreed with operations", "internal",
     "Hub operations managers", "own-09", "Reporting suite v1", "own-09",
     314, "delivered", "medium", 0.2, 8, ["ms-26"], ["ben-08"], []),

    # --- Change, training and readiness ------------------------------------
    ("DEP-59", "Training environment refreshed with configured TMS", "internal",
     "TMS Delivery", "own-05", "Super-user training", "own-10",
     334, "at-risk", "high", 0.5, 11, ["ms-30"], ["ben-06"], ["DEP-25"]),
    ("DEP-60", "Translated training material, six languages", "vendor",
     "Lingua Partners", "own-10", "Super-user training", "own-10",
     340, "on-track", "medium", 0.3, 9, ["ms-30"], ["ben-06"], []),
    ("DEP-61", "Release of super-users from operational rosters", "internal",
     "Hub operations managers", "own-15", "Super-user training", "own-10",
     346, "at-risk", "high", 0.55, 13, ["ms-30"], ["ben-06"], ["DEP-60"]),
    ("DEP-62", "Works council agreement on new roles", "regulatory",
     "European works council", "own-10", "Go-live readiness review", "own-15",
     366, "at-risk", "critical", 0.5, 24, ["ms-31"], ["ben-03", "ben-06"], ["DEP-20"]),
    ("DEP-63", "Cutover rehearsal window agreed with operations", "internal",
     "Regional operations", "own-15", "Go-live readiness review", "own-15",
     384, "on-track", "high", 0.35, 10, ["ms-31"], ["ben-04"], ["DEP-61"]),
    ("DEP-64", "Run organisation resourcing approved", "internal",
     "Operations leadership", "own-01", "Benefit handover", "own-11",
     404, "on-track", "high", 0.3, 15, ["ms-32"], ["ben-01", "ben-08"], ["DEP-57"]),
    ("DEP-65", "Benefit measurement baseline agreed with finance", "internal",
     "Group Finance", "own-11", "Benefit handover", "own-11",
     400, "at-risk", "high", 0.4, 12, ["ms-32"], ["ben-01", "ben-05"], ["DEP-10"]),
    ("DEP-66", "Cross-programme alignment with Commerce Replatform", "cross-program",
     "Commerce Replatform programme", "own-02", "Customer launch", "own-01",
     406, "at-risk", "high", 0.45, 20, ["ms-32"], ["ben-04", "ben-08"], []),
    ("DEP-67", "Cross-programme alignment with Finance Consolidation", "cross-program",
     "Finance Consolidation programme", "own-11", "Reporting suite v1", "own-09",
     348, "at-risk", "medium", 0.4, 16, ["ms-26"], ["ben-05"], []),
]

# Risks attached to dependencies, wired from orion_risk.
DEP_RISKS = {
    "DEP-01": ["rsk-01"],
    "DEP-02": ["rsk-01", "rsk-03"],
    "DEP-03": ["rsk-02"],
    "DEP-04": ["rsk-02"],
    "DEP-05": ["rsk-02", "rsk-24"],
    "DEP-07": ["rsk-04"],
    "DEP-09": ["rsk-09"],
    "DEP-10": ["rsk-09", "rsk-27"],
    "DEP-11": ["rsk-06"],
    "DEP-12": ["rsk-07"],
    "DEP-13": ["rsk-06"],
    "DEP-14": ["rsk-06", "rsk-33"],
    "DEP-15": ["rsk-19"],
    "DEP-19": ["rsk-31"],
    "DEP-20": ["rsk-20"],
    "DEP-26": ["rsk-22"],
    "DEP-27": ["rsk-13"],
    "DEP-28": ["rsk-13"],
    "DEP-35": ["rsk-02"],
    "DEP-36": ["rsk-15"],
    "DEP-41": ["rsk-11"],
    "DEP-43": ["rsk-14"],
    "DEP-44": ["rsk-14", "rsk-15"],
    "DEP-49": ["rsk-33"],
    "DEP-50": ["rsk-03"],
    "DEP-54": ["rsk-11"],
    "DEP-59": ["rsk-17"],
    "DEP-61": ["rsk-17"],
    "DEP-62": ["rsk-20"],
    "DEP-65": ["rsk-27"],
    "DEP-66": ["rsk-24"],
    "DEP-67": ["rsk-27"],
}


def dep_id(ref):
    return "dep-" + ref.split("-")[1]


def build_dependencies():
    out = []
    for (ref, name, dtype, up, upo, down, downo, due, status, crit, prob, delay,
         milestones, benefits, preds) in DEPENDENCIES:
        out.append({
            "id": dep_id(ref),
            "ref": ref,
            "name": name,
            "description": up + " must provide " + name.lower() + " to " + down + " by the due date for downstream work to proceed as planned.",
            "type": dtype,
            "upstream": up,
            "upstreamOwnerId": upo,
            "downstream": down,
            "downstreamOwnerId": downo,
            "dueDate": day(due),
            "status": status,
            "criticality": crit,
            "delayProbability": prob,
            "potentialDelayDays": delay,
            "affectedMilestoneIds": list(milestones),
            "affectedBenefitIds": list(benefits),
            "predecessorIds": [dep_id(p) for p in preds],
            "linkedRiskIds": list(DEP_RISKS.get(ref, [])),
        })
    return out
