"""ORION change requests.

Tuple order: id, ref, title, requester, raised, reason, scopeImpact, cost,
days, resource, riskImpact, benefitImpact, workstreams, milestones, depRefs,
benefits, risks, decision, decisionMaker, decisionOffset, rationale, status,
description
"""

CHANGES = [
    ("chg-01", "CHG-01", "Add Slovenia to cutover wave 1", "own-04", 268,
     "Commercial pressure to consolidate Adriatic flows a quarter earlier than planned.",
     "Wave 1 grows from two countries to three, adding 640 lanes.", 185_000, 9,
     "Two additional network analysts for eleven weeks.",
     "Increases cutover concentration risk on a single weekend.", 240_000,
     ["ws-net", "ws-car"], ["ms-05", "ms-18"], ["DEP-20"], ["ben-01"], ["rsk-29"],
     "approved", "own-01", 284,
     "Accepted because the incremental freight saving of 240k exceeds the delivery cost, and the additional cutover risk is contained by the existing rehearsal control.",
     "implemented",
     "Extend the first physical cutover wave to include Slovenian domestic and cross-border flows."),
    ("chg-02", "CHG-02", "Defer Frankfurt automation to a phase 2 investment", "own-08", 292,
     "Capital constraint after the Milan cost position and the supplier capacity shortfall.",
     "Removes Frankfurt goods-to-person automation from programme scope.", -640_000, 0,
     "Releases four automation engineers from month eleven.",
     "Removes Frankfurt automation delivery risk but concentrates the whole automation benefit on Milan.", -480_000,
     ["ws-wms", "ws-net"], ["ms-05"], ["DEP-52"], ["ben-01"], ["rsk-06"],
     "approved", "own-01", 306,
     "Approved on capital grounds. Accepted that 480k of benefit moves to phase 2 and that Milan now carries the whole automation benefit case, which raises the consequence of the supplier risk.",
     "implemented",
     "Remove the Frankfurt automation scope from the programme and re-plan it as a separate phase 2 investment."),
    ("chg-03", "CHG-03", "Extend hypercare from four to eight weeks", "own-05", 318,
     "The two-wave go-live extends the period during which both platforms operate.",
     "No functional scope change, extends the support period.", 148_000, 0,
     "Vendor hypercare team retained four weeks longer.",
     "Reduces post cutover operational and customer impact risk.", 0,
     ["ws-tms"], ["ms-10", "ms-31"], ["DEP-29"], [], ["rsk-25", "rsk-18"],
     "approved", "own-02", 330,
     "Approved within delegated authority. The cost is small relative to the customer impact exposure it reduces, and the two-wave plan made the original four week window untenable.",
     "implemented",
     "Extend vendor and internal hypercare cover to eight weeks to match the revised two-wave cutover."),
    ("chg-04", "CHG-04", "Add two integration engineers to the carrier API workstream", "own-06", 306,
     "The vendor specification gap requires an in-house adapter that was not in the original plan.",
     "Adds the invoice message adapter as an in-scope deliverable.", 172_000, -6,
     "Two contract integration engineers for five months.",
     "Reduces dependence on the vendor schema for go-live.", 0,
     ["ws-int"], ["ms-13", "ms-14"], ["DEP-01"], ["ben-04"], ["rsk-01", "rsk-03"],
     "approved", "own-01", 316,
     "Approved because it converts a vendor dependency the programme cannot control into internal work it can. The six day schedule recovery was the deciding factor.",
     "implemented",
     "Fund two additional integration engineers to build and test the interim invoice message adapter."),
    ("chg-05", "CHG-05", "Reduce reporting suite v1 to twelve core reports", "own-09", 350,
     "Data quality remediation will not complete in time to support the full reporting set, so the choice is scope or date.",
     "Removes 19 of 31 reports from v1 and moves them to a v1.1 release.", -85_000, -16,
     "No change to the team, the same team delivers less in the same window.",
     "Reduces the risk that reporting is rejected at acceptance, but leaves the run organisation without nine benefit reports at handover.", -260_000,
     ["ws-ctl", "ws-chg"], ["ms-26", "ms-20", "ms-32"], ["DEP-09", "DEP-10"], ["ben-04", "ben-08"],
     ["rsk-04", "rsk-09", "rsk-27"],
     "pending", None, None, None, "in-review",
     "Cut reporting suite v1 to the twelve reports that reconcile cleanly today, deferring the remainder until master data remediation completes."),
    ("chg-06", "CHG-06", "Replace the in-house customs interface with a broker managed service", "own-07", 344,
     "The broker has not released an interface specification and has offered a managed service instead.",
     "Removes the customs interface build, adds a managed service integration and an annual service fee.", 265_000, -12,
     "Releases one integration engineer, adds a vendor management overhead.",
     "Removes the certification risk but creates a long-term third party operational dependency.", -60_000,
     ["ws-car", "ws-int"], ["ms-19", "ms-05"], ["DEP-43", "DEP-44"], ["ben-07"], ["rsk-14", "rsk-15"],
     "escalated", None, None, None, "in-review",
     "Buy the broker managed customs service instead of building the declaration interface in house."),
    ("chg-07", "CHG-07", "Open Milan with two pick stations instead of three", "own-08", 356,
     "The supplier capacity shortfall makes three pick stations undeliverable for wave 1.",
     "Reduces day one automation capacity by roughly one third.", -210_000, -14,
     "No change during delivery, adds a later installation phase.",
     "Reduces the schedule risk on commissioning but caps early throughput.", -420_000,
     ["ws-wms"], ["ms-22", "ms-23", "ms-24"], ["DEP-11", "DEP-13"], ["ben-03"], ["rsk-06", "rsk-08"],
     "pending", None, None, None, "in-review",
     "Commission the Milan hub with two of the three planned pick stations and install the third in a later phase."),
    ("chg-08", "CHG-08", "Add an early penetration test cycle", "own-13", 322,
     "A single end-stage security gate leaves no time to remediate a critical finding.",
     "Adds one additional test cycle on completed integration patterns.", 62_000, 0,
     "External test vendor for two additional weeks.",
     "Materially reduces the chance that a critical finding is discovered inside the cutover window.", 0,
     ["ws-int"], ["ms-14"], ["DEP-04"], [], ["rsk-02", "rsk-28"],
     "approved", "own-02", 332,
     "Approved within delegated authority. Cheap relative to the consequence of failing the security gate at cutover.",
     "implemented",
     "Split penetration testing into an early exploratory cycle and a late confirmatory cycle."),
    ("chg-09", "CHG-09", "Extend customs compliance training to tier 2 carriers", "own-07", 338,
     "Tier 2 carriers handle 31% of cross-border volume but were excluded from the training scope.",
     "Adds 22 carriers to the compliance training programme.", 74_000, 0,
     "One compliance trainer for eight weeks.",
     "Reduces customs correction and penalty exposure across the tier 2 base.", 130_000,
     ["ws-car", "ws-chg"], ["ms-18"], ["DEP-46"], ["ben-07"], ["rsk-14"],
     "deferred", "own-02", 358,
     "Deferred to the phase 2 backlog. The benefit is credible but the compliance team cannot absorb it before go-live without displacing tier 1 readiness work.",
     "decided",
     "Include tier 2 carriers in the customs compliance training curriculum."),
    ("chg-10", "CHG-10", "Move network cutover wave 1 by three weeks", "own-04", 360,
     "Automation commissioning and works council consultation both land inside the current cutover window.",
     "No scope change, moves the wave 1 cutover date and the dependent readiness gate.", 96_000, 21,
     "Extends the programme team by three weeks.",
     "Reduces cutover concentration and readiness risk, increases cost and delays benefit start.", -310_000,
     ["ws-net", "ws-wms", "ws-chg"], ["ms-05", "ms-31", "ms-32"], ["DEP-20", "DEP-62"], ["ben-01", "ben-05"],
     ["rsk-06", "rsk-20", "rsk-29"],
     "escalated", None, None, None, "in-review",
     "Move the wave 1 physical cutover three weeks later to separate it from automation commissioning and the works council outcome."),
    ("chg-11", "CHG-11", "Split the TMS go-live into two waves", "own-05", 296,
     "A single go-live across all lanes concentrates too much risk in one weekend given the UAT position.",
     "Splits the cutover into wave 1 and wave 2 with a six week interval.", 128_000, 12,
     "Extends the delivery and hypercare teams by six weeks.",
     "Substantially reduces cutover and rollback risk, adds a period of dual running.", -140_000,
     ["ws-tms", "ws-int"], ["ms-10", "ms-31"], ["DEP-05", "DEP-29"], ["ben-04", "ben-09"],
     ["rsk-18", "rsk-13", "rsk-21"],
     "approved", "own-01", 312,
     "Approved. The reduction in cutover risk was judged to outweigh 128k of cost and a twelve day delay to full benefit start, on the basis that a failed single cutover would cost materially more.",
     "implemented",
     "Deliver the TMS cutover in two waves rather than a single all-lanes go-live."),
    ("chg-12", "CHG-12", "Retain the legacy transport system in parallel for six months", "own-05", 334,
     "Concern that a two-wave go-live leaves part of the estate exposed if the new platform underperforms.",
     "Adds six months of legacy licence, hosting and support.", 310_000, 0,
     "Retains two legacy support staff for six months.",
     "Would remove the fallback risk but at material cost, and it defers the decommission benefit.", -600_000,
     ["ws-tms"], ["ms-28"], ["DEP-30"], ["ben-09"], ["rsk-21"],
     "rejected", "own-01", 348,
     "Rejected. Six months of parallel running costs 310k and defers the entire 600k decommission benefit, while the fallback it buys is already covered by the two-wave plan and extended hypercare.",
     "decided",
     "Keep the legacy transport platform live in parallel for six months after wave 2 as a fallback."),
    ("chg-13", "CHG-13", "Add three data quality contractors for three months", "own-12", 330,
     "Defect arrival rate exceeds the clearance rate of the existing team.",
     "No scope change, adds temporary remediation capacity.", 118_000, -8,
     "Three contractors for thirteen weeks.",
     "Increases the chance of hitting the remediation exit threshold before the reporting gate.", 0,
     ["ws-int"], ["ms-15", "ms-26"], ["DEP-07"], ["ben-05"], ["rsk-04"],
     "approved", "own-02", 340,
     "Approved within delegated authority. Cheapest available lever against the largest single driver of the reporting and benefit measurement risk.",
     "implemented",
     "Fund three additional data quality contractors to accelerate the master data remediation backlog."),
]
