"""ORION decision log.

Tuple order: id, ref, title, context, owner, decisionMaker, forum,
requiredOffset, decidedOffset, reviewOffset, status, options, chosenIndex,
rationale, expectedOutcome, actualOutcome, score, risks, changes, benefits,
milestones, evidence
Option tuple: label, pros, cons, cost, scheduleDays, residualRiskNote
Evidence tuple: label, kind, dateOffset, source, confidence
"""

DECISIONS = [
    ("dec-01", "DEC-01", "Approve the seven-hub target network",
     "The network study produced three viable options: keep eleven sites, consolidate to nine, or consolidate to seven with two new automated hubs.",
     "own-04", "own-01", "Investment Committee", 88, 96, 240, "decided",
     [("Retain eleven sites", ["No transition risk", "No capital required"],
       ["Forgoes the entire freight saving", "Leaves the cost base uncompetitive"], 0, 0,
       "Freight cost gap persists at 412 per load."),
      ("Consolidate to nine sites", ["Lower transition risk", "Roughly half the capital"],
       ["Only 55% of the available saving", "Two hubs remain sub-scale"], 4_100_000, 300,
       "Residual sub-scale hub risk on two sites."),
      ("Consolidate to seven with automation", ["Full 3.6M freight saving", "Enables the automation productivity benefit"],
       ["Highest capital and transition risk", "Two new sites to commission"], 8_400_000, 425,
       "Concentration of benefit on two new hubs.")],
     2,
     "Chose the seven-hub option because it is the only option that closes the cost-to-serve gap, and the incremental transition risk is manageable with staged cutover waves.",
     "Freight cost per load reduced from 412 to 318 within twelve months of the final cutover.",
     "Network model validated at 8% peak headroom and the first 1.18M of freight saving has been realised. The automation dependency has proved more fragile than assumed at the time.",
     4, ["rsk-29", "rsk-30"], ["chg-01", "chg-02"], ["ben-01"], ["ms-02", "ms-05"],
     [("Network scenario model v4", "document", 44, "Network Design", "verified"),
      ("Cost-to-serve baseline reconciliation", "metric", 42, "Group Finance", "verified")]),

    ("dec-02", "DEC-02", "Sequence security testing in parallel with UAT rather than after it",
     "The assurance model places penetration testing as a single gate after integration completes, which leaves no remediation window before cutover.",
     "own-13", "own-02", "Programme Board", 316, 332, 400, "decided",
     [("Keep the single end-stage gate", ["No additional cost", "Simplest to manage"],
       ["A critical finding cannot be remediated in time", "Assurance failure would stop the gate"], 0, 0,
       "Full residual security gate risk retained."),
      ("Add an early exploratory cycle", ["Findings surface while there is time to fix", "Confirmatory cycle stays as the gate"],
       ["62k additional test cost", "Requires patterns to be complete early"], 62_000, 0,
       "Residual risk limited to findings in late-built patterns.")],
     1,
     "Chose the two-cycle model. The cost is immaterial against the consequence of failing the security gate inside the cutover window, and it converts an unmanageable late risk into a manageable early one.",
     "Critical security findings identified at least eight weeks before the go-live gate.",
     None, None, ["rsk-02", "rsk-28"], ["chg-08"], ["ben-04"], ["ms-14"],
     [("Threat model register", "document", 341, "Security Architecture", "measured"),
      ("Assurance model review note", "document", 320, "Security and Compliance", "measured")]),

    ("dec-03", "DEC-03", "Reduce reporting suite scope or delay the reporting gate",
     "Master data remediation will not reach the exit threshold before the reporting gate, so nineteen of thirty-one reports cannot reconcile. The programme must either cut scope or move the date, and both affect benefit handover.",
     "own-09", "own-01", "Steering Committee", 374, None, None, "required",
     [("Cut v1 to twelve reconciling reports", ["Holds the gate date", "Nothing is shipped that cannot be trusted"],
       ["Run organisation lacks nine benefit reports at handover", "260k of benefit measurement deferred"], -85_000, -16,
       "Benefit measurement risk rises because the baseline cannot be evidenced."),
      ("Delay the reporting gate by six weeks", ["Full scope delivered", "Benefit measurement intact"],
       ["Delays benefit handover and the readiness gate", "Extends programme team cost"], 96_000, 42,
       "Schedule risk transfers onto the readiness gate."),
      ("Ship full scope with a known variance", ["No schedule or scope change"],
       ["Reporting would be rejected by finance", "Destroys confidence in programme numbers"], 0, 0,
       "Unacceptable: the acceptance criteria would not be met.")],
     None, None,
     "A reporting gate that finance accepts, with a documented plan for the deferred reports.",
     None, None, ["rsk-04", "rsk-09", "rsk-27"], ["chg-05"], ["ben-08", "ben-04"], ["ms-26", "ms-32"],
     [("Period 11 reconciliation pack", "metric", 350, "Group Finance", "verified"),
      ("Master data defect trend", "metric", 371, "Data Quality", "verified"),
      ("Metric dictionary status", "document", 344, "Finance Business Partner", "measured")]),

    ("dec-04", "DEC-04", "Split the TMS go-live into two waves",
     "The UAT defect position and the rollback rehearsal result both indicate that a single all-lanes cutover carries more risk than the programme can absorb in one weekend.",
     "own-05", "own-01", "Programme Board", 300, 312, 396, "decided",
     [("Single all-lanes cutover", ["Fastest route to full benefit", "One hypercare period"],
       ["Concentrates all cutover risk in one weekend", "Rollback proven only at five hours ten minutes"], 0, 0,
       "Full cutover and rollback risk retained."),
      ("Two waves six weeks apart", ["Halves the exposed volume per cutover", "Learning applied to wave 2"],
       ["128k additional cost", "Twelve day delay to full benefit", "A period of dual running"], 128_000, 12,
       "Residual risk concentrated on wave 1 only.")],
     1,
     "Chose two waves. A failed single cutover would cost materially more than 128k in customer credits and premium freight, and the rehearsal evidence did not support a single-shot approach.",
     "Wave 1 cutover completed without a customer-visible service failure.",
     None, None, ["rsk-18", "rsk-13", "rsk-21"], ["chg-11", "chg-03"], ["ben-04", "ben-09"], ["ms-10", "ms-31"],
     [("Cutover rehearsal 1 report", "test-result", 354, "TMS Delivery", "verified"),
      ("UAT defect burn-down", "metric", 371, "TMS Delivery", "verified")]),

    ("dec-05", "DEC-05", "Build the customs interface or buy the broker managed service",
     "The broker will not release an interface specification and has offered a managed service. Building without a specification is not possible, so the choice is to buy, to change broker, or to run manual declarations.",
     "own-07", "own-01", "Steering Committee", 376, None, None, "required",
     [("Buy the broker managed service", ["Removes the certification risk", "Twelve days faster"],
       ["265k cost and an ongoing service fee", "Creates a long-term third party dependency"], 265_000, -12,
       "Certification risk removed, operational dependency created."),
      ("Change customs broker", ["Regains control of the interface"],
       ["Re-tender takes at least sixteen weeks", "Would miss the wave 1 cross-border cutover"], 180_000, 60,
       "Schedule risk becomes unacceptable."),
      ("Run manual declarations for wave 1", ["No capital cost", "No new dependency"],
       ["Penalty and delay exposure on every cross-border load", "Erodes the compliance benefit"], 40_000, 0,
       "Customs penalty exposure retained in full.")],
     None, None,
     "Automated customs declarations available for cross-border loads before the wave 1 cutover.",
     None, None, ["rsk-14", "rsk-15"], ["chg-06"], ["ben-07"], ["ms-19"],
     [("Broker correspondence log", "document", 328, "Carrier Compliance", "verified"),
      ("Manual declaration cost estimate", "metric", 344, "Finance Business Partner", "measured")]),

    ("dec-06", "DEC-06", "Reduce Milan automation to two pick stations for wave 1",
     "The supplier capacity shortfall makes three pick stations undeliverable for wave 1. Opening with two caps throughput but protects the commissioning date.",
     "own-08", "own-01", "Steering Committee", 378, None, 420, "scheduled",
     [("Open with three stations as planned", ["Full benefit from day one"],
       ["Depends on a supplier date that does not exist", "Would delay commissioning by an unknown period"], 0, 28,
       "Unbounded schedule risk on a single supplier."),
      ("Open with two stations, install the third later", ["Protects the commissioning date", "Reduces supplier dependency for wave 1"],
       ["Caps day one throughput by a third", "420k of benefit deferred"], -210_000, -14,
       "Benefit timing risk replaces schedule risk."),
      ("Delay Milan automation entirely to phase 2", ["Removes the automation risk from the programme"],
       ["Loses 1.8M of productivity benefit from the business case"], -1_100_000, -30,
       "Benefit case materially weakened.")],
     None, None,
     "Commissioning completed on the current forecast date with a documented plan for the third station.",
     None, None, ["rsk-06", "rsk-08", "rsk-33"], ["chg-07"], ["ben-03"], ["ms-22", "ms-23"],
     [("Supplier capacity correspondence", "document", 322, "Vendor Management", "verified"),
      ("Throughput simulation, two versus three stations", "test-result", 358, "Warehouse Automation", "measured")]),

    ("dec-07", "DEC-07", "Accept or mitigate the Commerce Replatform interface collision",
     "Both programmes booked change windows on the same order management interface. Portfolio governance reviewed scope but not technical collisions.",
     "own-02", "own-02", "Portfolio Board", 344, 350, 410, "decided",
     [("Accept and coordinate informally", ["No process overhead"],
       ["Relies on individuals noticing collisions", "Has already failed once"], 0, 0,
       "Collision risk essentially unchanged."),
      ("Establish a shared change calendar with collision review", ["Systematic detection", "Applies to future changes too"],
       ["Adds a fortnightly review", "Requires both programmes to publish early"], 12_000, 0,
       "Residual risk limited to unpublished changes.")],
     1,
     "Chose the shared calendar. The overhead is one fortnightly meeting against an exposure that had already materialised once and would have recurred.",
     "No further interface collisions between the two programmes before wave 2.",
     "No collisions since the calendar was introduced in period 10, and two potential collisions were detected and re-sequenced.",
     5, ["rsk-24"], [], [], ["ms-10"],
     [("Portfolio change calendar", "system-record", 366, "Programme Office", "verified"),
      ("Collision review minutes", "meeting", 368, "Programme Office", "measured")]),

    ("dec-08", "DEC-08", "Select the master data remediation approach",
     "Two options were available: fix defects in the source systems, or remediate in a staging layer during migration. The staging option was faster and cheaper.",
     "own-12", "own-02", "Programme Board", 300, 308, 360, "decided",
     [("Remediate at source", ["Fixes the defect permanently", "Improves legacy reporting too"],
       ["Requires regional system changes", "Slower and needs regional IT capacity"], 240_000, 30,
       "Defect recurrence risk removed."),
      ("Remediate in the staging layer", ["Faster and cheaper", "No regional system change"],
       ["Source systems keep producing defects", "Every future load needs the same remediation"], 90_000, 0,
       "Defect recurrence risk retained in full.")],
     1,
     "Chose staging layer remediation on cost and speed grounds, accepting that the source systems would continue to produce defects until the legacy platforms are decommissioned.",
     "Master data defect rate below 1.5% at the migration exit gate.",
     "The approach cleared the historic backlog but did not stop new defects arriving. Arrival rate now exceeds clearance rate and the exit gate has moved twice. Remediating at source would have been slower but would have held.",
     2, ["rsk-04", "rsk-09"], ["chg-13"], ["ben-05"], ["ms-15"],
     [("Defect arrival versus clearance trend", "metric", 371, "Data Quality", "verified"),
      ("Remediation approach options paper", "document", 302, "Data Quality", "measured")]),

    ("dec-09", "DEC-09", "Approve extended hypercare for the two-wave go-live",
     "Splitting the go-live into two waves extended the period during which both platforms operate, beyond the four weeks of hypercare originally funded.",
     "own-05", "own-02", "Programme Board", 326, 330, 398, "decided",
     [("Keep four weeks of hypercare", ["No additional cost"],
       ["Wave 2 would run without vendor cover", "Support gap during dual running"], 0, 0,
       "Post cutover support risk retained."),
      ("Extend to eight weeks", ["Cover across both waves", "Vendor engineers retained"],
       ["148k additional cost"], 148_000, 0,
       "Support risk substantially reduced.")],
     1,
     "Chose the extension. The two-wave decision created the gap, so funding cover for it was a direct consequence rather than a new choice.",
     "No unsupported period during dual running, and wave 2 covered by the same team that ran wave 1.",
     "Hypercare rota confirmed and the vendor contract amended. No dual running gap remains in the plan.",
     4, ["rsk-25", "rsk-18"], ["chg-03"], [], ["ms-10"],
     [("Hypercare capacity model v3", "document", 360, "TMS Delivery", "verified")]),

    ("dec-10", "DEC-10", "Approve the carrier data sharing fallback position",
     "Three tier 1 carriers rejected the standard unlimited liability clause for visibility data. Without their data the control tower cannot cover 38% of volume.",
     "own-07", "own-01", "Steering Committee", 380, None, None, "required",
     [("Hold the standard clause", ["Consistent contractual position", "No liability exposure"],
       ["Three carriers withhold data", "Control tower coverage drops to 62%"], 0, 0,
       "Benefit risk on the service level uplift."),
      ("Apply the pre-agreed fallback wording", ["Unblocks the data", "Already legally reviewed"],
       ["Accepts a capped liability for data accuracy", "Sets a precedent for tier 2 negotiations"], 0, -21,
       "Liability accepted at a capped level."),
      ("Source visibility data from a third party aggregator", ["No carrier negotiation needed"],
       ["Adds an annual fee", "Lower data granularity"], 140_000, -14,
       "Data quality risk on ETA accuracy.")],
     None, None,
     "Visibility data flowing from all tier 1 carriers before the control tower full rollout.",
     None, None, ["rsk-11", "rsk-15", "rsk-10"], [], ["ben-08"], ["ms-25", "ms-28"],
     [("Carrier legal position summary", "document", 340, "Group Legal", "verified"),
      ("Control tower coverage analysis", "metric", 358, "Control Tower", "measured")]),
]
