"""ORION risk domain: causes, controls, actions, risks, issues, assumptions.

Relationships are declared once. gen_orion.py inverts control.linkedRiskIds,
action.linkedRiskIds and cause.linkedRiskIds onto the risks so both directions
can never disagree.
"""

from orion_core import day, STATUS, START
from datetime import timedelta

STATUS_OFFSET = (STATUS - START).days  # 373


# ref, title, category, isRoot, frequency, owner, whyChain, linked risks, linked issues
CAUSES = [
    ("CSE-01", "Carrier API specification issued incomplete by the vendor", "process", True, 34, "own-14",
     ["The specification was released without the invoice message schema",
      "Because the vendor treated invoicing as a phase 2 item",
      "Because the contract statement of work did not name invoice messages explicitly",
      "Because the requirement was captured in a workshop but never written into the SOW",
      "Because there was no requirement traceability check before contract signature"],
     ["rsk-01", "rsk-03"], ["iss-03"]),
    ("CSE-02", "No single owner for master data quality across regions", "management", True, 41, "own-12",
     ["Defects were not fixed because nobody was accountable for the attribute",
      "Because data ownership was defined by system, not by attribute",
      "Because the legacy operating model had one system per region",
      "Because regions were run as separate profit centres",
      "Because the target operating model was never translated into data ownership"],
     ["rsk-04", "rsk-09"], ["iss-01"]),
    ("CSE-03", "Manual re-keying between legacy systems introduces errors", "process", False, 29, "own-12",
     ["Address and weight fields differ between the two systems",
      "Because operators re-key data at the hub",
      "Because there is no interface between the regional systems"],
     ["rsk-04"], ["iss-01"]),
    ("CSE-04", "Supplier allocated the Milan build slot to another customer", "management", True, 12, "own-14",
     ["The Milan line lost its build slot",
      "Because the supplier prioritised a larger customer order",
      "Because our contract has no slot-protection clause",
      "Because the negotiation focused on unit price rather than delivery certainty"],
     ["rsk-06"], ["iss-05"]),
    ("CSE-05", "Utility connection lead times not reflected in the plan", "environment", True, 8, "own-04",
     ["The power upgrade will not complete before install",
      "Because the utility quoted a 26 week lead time",
      "Because the application was raised after the fit-out plan was baselined",
      "Because utility lead time was assumed to be inside the fit-out float"],
     ["rsk-07"], ["iss-04"]),
    ("CSE-06", "Test environments do not hold production-like data volumes", "technology", True, 22, "own-06",
     ["Defects appear only in production-like volumes",
      "Because the test environment holds 4% of production data",
      "Because data masking capacity was sized for functional testing only"],
     ["rsk-34", "rsk-05"], ["iss-06"]),
    ("CSE-07", "Business testers not released from operational duties", "people", True, 26, "own-15",
     ["UAT execution is behind plan",
      "Because testers attend only part time",
      "Because hub managers are measured on operational service, not programme delivery",
      "Because programme contribution is not in the hub manager scorecard"],
     ["rsk-13", "rsk-17"], ["iss-06", "iss-08"]),
    ("CSE-08", "Security testing scheduled after integration is complete", "process", True, 6, "own-13",
     ["Security findings arrive too late to fix cheaply",
      "Because penetration testing is a single gate at the end",
      "Because the assurance model is stage-gated rather than continuous"],
     ["rsk-02", "rsk-28"], []),
    ("CSE-09", "Reporting definitions differ between operations and finance", "measurement", True, 19, "own-11",
     ["Reported cost does not reconcile to the ledger",
      "Because operations count movements and finance counts invoices",
      "Because no common metric dictionary was agreed",
      "Because the reporting requirement was gathered separately by each function"],
     ["rsk-09", "rsk-27"], ["iss-02"]),
    ("CSE-10", "Carrier legal teams reject standard data sharing clause", "policy", False, 14, "own-07",
     ["Visibility data is not flowing from three carriers",
      "Because their legal teams rejected the standard clause",
      "Because the clause assigns unlimited liability for data accuracy"],
     ["rsk-11", "rsk-15"], []),
    ("CSE-11", "Customs broker operates a proprietary undocumented interface", "technology", False, 9, "own-07",
     ["The customs interface cannot be built to specification",
      "Because the broker has not released an interface specification",
      "Because their platform is a bespoke legacy system"],
     ["rsk-14"], ["iss-07"]),
    ("CSE-12", "Single deep specialist holds the integration design knowledge", "people", True, 5, "own-06",
     ["Integration decisions stall when one architect is unavailable",
      "Because the design rationale is not documented",
      "Because the team ran at 100% delivery utilisation with no documentation time"],
     ["rsk-16"], ["iss-12"]),
    ("CSE-13", "Works council was engaged after the role design was fixed", "management", True, 4, "own-10",
     ["The works council lodged a formal objection",
      "Because they saw the role design as a fait accompli",
      "Because consultation started after the design was signed off",
      "Because the change plan treated consultation as a communication step"],
     ["rsk-20", "rsk-36"], ["iss-11"]),
    ("CSE-14", "Local labour market for warehouse operatives is tight", "environment", False, 11, "own-15",
     ["Recruitment is behind the ramp-up curve",
      "Because applications per vacancy have halved",
      "Because three competing distribution centres opened within 20km"],
     ["rsk-19"], []),
    ("CSE-15", "Operational business rules were still being agreed during build", "process", True, 24, "own-05",
     ["Configuration is being reworked",
      "Because business rules changed after the build freeze",
      "Because the rules were never formally baselined",
      "Because the design authority approved principles rather than rules"],
     ["rsk-22", "rsk-13"], []),
    ("CSE-16", "Automation throughput modelled on ideal order profile", "measurement", True, 7, "own-08",
     ["Measured throughput is below the contractual figure",
      "Because the model assumed a uniform order profile",
      "Because the profile used was an annual average, not a peak week"],
     ["rsk-08", "rsk-33"], []),
    ("CSE-17", "Two programmes are changing the same order management interface", "management", True, 6, "own-02",
     ["Both programmes have booked the same interface change window",
      "Because there is no shared change calendar",
      "Because portfolio governance reviews scope but not technical collisions"],
     ["rsk-24"], []),
    ("CSE-18", "Linehaul rates are exposed to spot market movement", "environment", False, 15, "own-11",
     ["Forecast savings are eroding",
      "Because 34% of linehaul volume sits on spot rates",
      "Because the tender was deliberately staged to keep flexibility"],
     ["rsk-32", "rsk-12"], []),
    ("CSE-19", "Carrier invoice formats vary by country", "process", False, 31, "own-07",
     ["Invoice matching fails for cross-border loads",
      "Because six invoice formats are in use",
      "Because each country onboarded carriers to a local standard"],
     ["rsk-26"], []),
    ("CSE-20", "Hypercare model sized on single-wave go-live", "process", False, 3, "own-05",
     ["Support capacity looks thin for the revised plan",
      "Because hypercare was sized before the go-live was split into waves",
      "Because the resourcing model was built from the original single-cutover assumption",
      "Because the wave decision was taken after the support plan was baselined"],
     ["rsk-25"], []),
    ("CSE-21", "Run organisation roles not yet funded", "management", True, 5, "own-01",
     ["Knowledge transfer has no receiving team",
      "Because run roles are not funded until the next budget cycle",
      "Because the business case treated run cost as a later decision"],
     ["rsk-41", "rsk-10"], []),
    ("CSE-22", "Environmental permit carries a night-movement condition", "policy", False, 2, "own-04",
     ["Night trunking at Milan may be restricted",
      "Because the permit limits movements between 23:00 and 05:00",
      "Because the site sits inside a residential noise zone"],
     ["rsk-40", "rsk-29"], []),
]


# ref, name, type, owner, frequency, design, operating, evidence, lastTested,
# nextTest, automated, status, linked risks, description
CONTROLS = [
    ("CTL-01", "Weekly vendor delivery review with contractual escalation", "directive", "own-14", "weekly",
     0.7, 0.55, "Minuted vendor review pack, week 47", 352, 359, False, "degraded", ["rsk-01", "rsk-21", "rsk-28"],
     "Standing weekly review of vendor deliverables against the contract schedule, with a written escalation at two consecutive misses."),
    ("CTL-02", "Requirement traceability matrix reviewed at each gate", "preventive", "own-05", "event-driven",
     0.75, 0.7, "Traceability matrix v6, design authority minute", 330, 380, False, "active", ["rsk-01", "rsk-22"],
     "Every requirement is traced to a configuration object and a test case before a gate can close."),
    ("CTL-03", "Continuous static and dependency scanning in the build pipeline", "detective", "own-13", "continuous",
     0.8, 0.78, "Pipeline scan dashboard, daily", 370, 377, True, "active", ["rsk-02", "rsk-28"],
     "Automated SAST and software composition analysis on every commit, blocking merges on high findings."),
    ("CTL-04", "Threat modelling workshop per integration pattern", "preventive", "own-13", "event-driven",
     0.65, 0.5, "Threat model register, 7 of 11 patterns", 341, 366, False, "degraded", ["rsk-02", "rsk-28"],
     "Structured threat model completed before each integration pattern is built."),
    ("CTL-05", "Automated data quality rules on the eight critical attributes", "detective", "own-12", "daily",
     0.85, 0.8, "Data quality dashboard, daily defect count", 371, 378, True, "active", ["rsk-04", "rsk-09", "rsk-34"],
     "Rule-based validation runs nightly across the critical attribute set and raises defects into the remediation queue."),
    ("CTL-06", "Data ownership matrix with named attribute owners", "directive", "own-12", "monthly",
     0.6, 0.45, "Ownership matrix v3, 6 of 8 attributes assigned", 349, 379, False, "degraded", ["rsk-04"],
     "Named accountable owner per critical data attribute, reviewed monthly with the data governance forum."),
    ("CTL-07", "Full volume migration rehearsal before each cutover", "detective", "own-06", "event-driven",
     0.8, 0.75, "Dry run 1 report, dry run 2 scheduled", 251, 355, False, "active", ["rsk-04", "rsk-05", "rsk-34"],
     "Production-volume extract, transform and load rehearsal with completeness and defect reporting."),
    ("CTL-08", "Contractual slot protection and liquidated damages", "preventive", "own-14", "event-driven",
     0.5, 0.3, "Contract schedule 4, no slot clause on Milan line", 137, 380, False, "degraded", ["rsk-06", "rsk-31"],
     "Delivery slot protection and liquidated damages in supply contracts, applied where the clause exists."),
    ("CTL-09", "Dual sourcing assessment for long lead items", "preventive", "own-14", "quarterly",
     0.55, 0.4, "Long lead item register, 9 of 14 assessed", 320, 380, False, "degraded", ["rsk-06", "rsk-31", "rsk-21"],
     "Long lead items are assessed for an alternative source, with a switch cost and lead time recorded."),
    ("CTL-10", "Utility and permit lead time tracker", "detective", "own-04", "monthly",
     0.7, 0.65, "Permit tracker, all 6 permits logged", 358, 388, False, "active", ["rsk-07", "rsk-40"],
     "Register of every external permit and utility connection with its quoted lead time and current status."),
    ("CTL-11", "Factory acceptance test with contractual throughput warranty", "detective", "own-08", "event-driven",
     0.85, 0.8, "FAT protocol signed by both parties", 300, 404, False, "active", ["rsk-08", "rsk-33"],
     "Throughput and availability are proven against the warranty before payment milestones release."),
    ("CTL-12", "Peak profile simulation before commissioning", "preventive", "own-08", "event-driven",
     0.6, 0.4, "Simulation run on annual average profile only", 310, 385, False, "degraded", ["rsk-08", "rsk-33"],
     "Discrete event simulation of the automation using real order profiles including peak week."),
    ("CTL-13", "Metric dictionary agreed jointly by operations and finance", "preventive", "own-11", "monthly",
     0.7, 0.5, "Dictionary v2, 31 of 48 metrics agreed", 344, 374, False, "degraded", ["rsk-09", "rsk-27"],
     "Single definition, source and owner per reported metric, signed off by both functions."),
    ("CTL-14", "Monthly reconciliation of reporting to the general ledger", "detective", "own-11", "monthly",
     0.8, 0.7, "Reconciliation pack, variance 4.1% in period 11", 350, 380, True, "active", ["rsk-09", "rsk-26"],
     "Automated reconciliation of programme reporting to finance with a variance threshold and escalation."),
    ("CTL-15", "Standard carrier data sharing clause with fallback wording", "preventive", "own-07", "event-driven",
     0.65, 0.55, "Legal playbook v4, fallback used with 5 carriers", 340, 385, False, "active", ["rsk-11", "rsk-15"],
     "Pre-agreed primary and fallback contract wording so carrier legal review does not restart negotiation."),
    ("CTL-16", "Data protection impact assessment before each new data flow", "preventive", "own-13", "event-driven",
     0.8, 0.75, "DPIA register, 9 of 11 flows assessed", 348, 383, False, "active", ["rsk-15", "rsk-28"],
     "No new personal data flow is enabled without a completed and approved impact assessment."),
    ("CTL-17", "Defect burn-down tracked daily against an exit curve", "detective", "own-05", "daily",
     0.75, 0.7, "UAT burn-down chart, daily", 371, 375, True, "active", ["rsk-13", "rsk-22", "rsk-34"],
     "Daily defect open and close rates plotted against the curve required to hit the UAT exit date."),
    ("CTL-18", "Named tester allocation confirmed in writing by hub managers", "directive", "own-15", "fortnightly",
     0.6, 0.4, "Allocation sheet, 62% of committed days delivered", 359, 373, False, "degraded", ["rsk-13", "rsk-17"],
     "Written commitment of named testers and training attendees, reviewed fortnightly with attendance actuals."),
    ("CTL-19", "Broker interface proof of concept before commitment", "preventive", "own-07", "event-driven",
     0.6, 0.35, "Proof of concept not yet started", None, 372, False, "planned", ["rsk-14"],
     "Working proof of concept against the broker interface before the design is committed."),
    ("CTL-20", "Key person cover plan with documented design decisions", "preventive", "own-06", "monthly",
     0.6, 0.5, "Decision log v11, cover named for 3 of 5 roles", 352, 382, False, "degraded", ["rsk-16", "rsk-41"],
     "Named deputy and a written decision log for every single-point-of-knowledge role."),
    ("CTL-21", "Works council consultation calendar with legal review", "preventive", "own-10", "monthly",
     0.7, 0.6, "Consultation calendar, minutes of 8 sessions", 356, 386, False, "active", ["rsk-20", "rsk-36"],
     "Scheduled consultation ahead of each design decision, with legal review of the position paper."),
    ("CTL-22", "Recruitment pipeline tracked against the ramp-up curve", "detective", "own-15", "weekly",
     0.7, 0.6, "Pipeline report, 71% of curve", 369, 376, True, "active", ["rsk-19"],
     "Weekly funnel report from application to start date against the operational ramp-up requirement."),
    ("CTL-23", "Cutover rehearsal with timed rollback", "detective", "own-05", "event-driven",
     0.8, 0.6, "Rehearsal 1 complete, rollback 5h 10m against 4h target", 354, 390, False, "degraded", ["rsk-18", "rsk-25"],
     "Full cutover rehearsal including a timed rollback to prove the exit path."),
    ("CTL-24", "Hypercare capacity model reviewed against the go-live plan", "preventive", "own-05", "monthly",
     0.65, 0.6, "Capacity model v3 aligned to two-wave plan", 360, 385, False, "active", ["rsk-25", "rsk-18"],
     "Support capacity is re-modelled whenever the go-live sequence changes."),
    ("CTL-25", "Three-way invoice match at cost, load and contract rate", "detective", "own-07", "continuous",
     0.85, 0.8, "Match exception report, 2.1% exception rate", 370, 377, True, "active", ["rsk-26", "rsk-12"],
     "Automated match of carrier invoice to executed load and contracted rate, with exception routing."),
    ("CTL-26", "Portfolio change calendar with technical collision review", "preventive", "own-02", "fortnightly",
     0.6, 0.55, "Change calendar, collision review added week 44", 366, 380, False, "active", ["rsk-24"],
     "Shared calendar of interface-affecting changes across programmes, reviewed for technical collisions."),
    ("CTL-27", "Rate exposure hedged through staged tender waves", "preventive", "own-11", "quarterly",
     0.55, 0.5, "Tender wave 2 award, 66% of volume on fixed rate", 344, 404, False, "active", ["rsk-32", "rsk-12"],
     "Volume is progressively moved from spot to fixed rate through staged tender waves."),
    ("CTL-28", "Benefit baseline signed off by finance before handover", "directive", "own-11", "event-driven",
     0.75, 0.4, "Baseline agreed for 4 of 9 benefits", 340, 400, False, "degraded", ["rsk-27", "rsk-10"],
     "Written finance agreement on the baseline, measure and reporting cadence for every benefit."),
    ("CTL-29", "Service level monitoring with customer impact alerting", "detective", "own-09", "continuous",
     0.75, 0.7, "OTIF dashboard, hourly refresh", 371, 378, True, "active", ["rsk-29", "rsk-30", "rsk-38"],
     "Continuous on-time in-full monitoring with alerting on customer-visible degradation."),
    ("CTL-30", "Model risk review and drift monitoring for predictive ETA", "preventive", "own-13", "quarterly",
     0.7, 0.5, "Model risk template submitted, review pending", 350, 380, False, "planned", ["rsk-35"],
     "Formal model risk assessment plus production drift monitoring before the ETA model is relied upon."),
    ("CTL-31", "Concentration limit per carrier per lane", "preventive", "own-07", "monthly",
     0.6, 0.55, "Concentration report, one lane above limit", 358, 388, False, "active", ["rsk-39", "rsk-11"],
     "No single carrier may exceed the agreed share of volume on a lane without an accepted exception."),
    ("CTL-32", "Knowledge transfer plan with run-organisation acceptance", "directive", "own-10", "monthly",
     0.65, 0.35, "Plan drafted, run roles unfunded", 352, 382, False, "degraded", ["rsk-41", "rsk-10", "rsk-36"],
     "Documented knowledge transfer with named receiving owners who formally accept each artefact."),
]


# ref, title, owner, dueOffset, completedOffset, status, priority, riskIds,
# issueIds, depRefs, expectedReduction, percentComplete, description
ACTIONS = [
    ("ACT-01", "Escalate carrier API specification gap to vendor executive sponsor", "own-14", 358, None, "overdue", "critical",
     ["rsk-01"], ["iss-03"], ["DEP-01"], 0.25, 60,
     "Formal contractual escalation to the Nordwind executive sponsor requiring a dated remediation plan for the invoice message schema."),
    ("ACT-02", "Build invoice message adapter in-house as a contingency", "own-06", 378, None, "in-progress", "critical",
     ["rsk-01", "rsk-03"], ["iss-03"], ["DEP-01"], 0.35, 45,
     "Interim adapter that translates the legacy invoice format so go-live is not dependent on the vendor schema."),
    ("ACT-03", "Bring forward penetration testing to a two-cycle model", "own-13", 356, 354, "complete", "high",
     ["rsk-02"], [], ["DEP-04"], 0.3, 100,
     "Split the single end-stage penetration test into an early cycle on completed patterns and a confirmatory cycle before sign-off."),
    ("ACT-04", "Recruit three data quality contractors for the remediation backlog", "own-12", 344, 341, "complete", "high",
     ["rsk-04"], ["iss-01"], ["DEP-07"], 0.2, 100,
     "Short-term capacity to clear the master data defect backlog to the exit threshold."),
    ("ACT-05", "Assign named owners to the two unassigned critical data attributes", "own-12", 366, None, "overdue", "critical",
     ["rsk-04"], ["iss-01"], ["DEP-07"], 0.15, 30,
     "Close the ownership gap on the two attributes that carry the largest defect counts."),
    ("ACT-06", "Negotiate a protected build slot for the Milan automation line", "own-14", 360, None, "overdue", "critical",
     ["rsk-06"], ["iss-05"], ["DEP-11"], 0.3, 40,
     "Contract amendment to secure a protected build slot with liquidated damages for further movement."),
    ("ACT-07", "Assess a phased automation go-live with two pick stations", "own-08", 383, None, "in-progress", "high",
     ["rsk-06", "rsk-08"], ["iss-05"], ["DEP-13"], 0.25, 55,
     "Option assessment for opening with reduced automation capacity while the third station is installed later."),
    ("ACT-08", "Expedite the Milan power upgrade with the utility", "own-04", 350, None, "overdue", "high",
     ["rsk-07"], ["iss-04"], ["DEP-12"], 0.2, 70,
     "Paid expedite request and a temporary generator option to de-couple install from the utility date."),
    ("ACT-09", "Re-run the automation simulation with peak week order profiles", "own-08", 378, None, "in-progress", "high",
     ["rsk-08", "rsk-33"], [], ["DEP-49"], 0.3, 35,
     "Replace the annual average profile with three real peak weeks and re-derive the achievable throughput."),
    ("ACT-10", "Agree the remaining 17 metric definitions with finance", "own-11", 388, None, "in-progress", "high",
     ["rsk-09", "rsk-27"], ["iss-02"], ["DEP-10"], 0.3, 65,
     "Joint workshop series to close the metric dictionary so reporting reconciles to the ledger."),
    ("ACT-11", "Deploy the fallback data sharing clause with the three holdout carriers", "own-07", 393, None, "in-progress", "high",
     ["rsk-11"], [], ["DEP-54"], 0.25, 50,
     "Use the pre-agreed fallback wording to unblock visibility data without reopening commercial terms."),
    ("ACT-12", "Run a proof of concept against the customs broker interface", "own-07", 398, None, "in-progress", "critical",
     ["rsk-14"], ["iss-07"], ["DEP-43"], 0.35, 25,
     "Prove a single declaration end to end before committing the interface design."),
    ("ACT-13", "Complete the outstanding two data protection impact assessments", "own-13", 403, None, "in-progress", "medium",
     ["rsk-15"], [], ["DEP-36"], 0.2, 60,
     "Close the assessment gap on the two carrier data flows still pending approval."),
    ("ACT-14", "Document integration design decisions and name a deputy architect", "own-06", 362, None, "overdue", "high",
     ["rsk-16"], ["iss-12"], [], 0.25, 45,
     "Written decision log plus a named deputy so integration decisions do not stall on one person."),
    ("ACT-15", "Add programme contribution to hub manager scorecards", "own-15", 356, None, "overdue", "high",
     ["rsk-17", "rsk-13"], ["iss-08"], ["DEP-61"], 0.3, 20,
     "Make tester and trainee release a measured objective for hub managers rather than a request."),
    ("ACT-16", "Re-run the cutover rehearsal to prove a rollback inside four hours", "own-05", 380, None, "in-progress", "critical",
     ["rsk-18"], [], ["DEP-63"], 0.35, 30,
     "Second rehearsal with the identified bottleneck steps automated, targeting a rollback under the agreed window."),
    ("ACT-17", "Launch a targeted recruitment campaign for the Milan hub", "own-15", 408, None, "in-progress", "high",
     ["rsk-19"], [], ["DEP-15"], 0.25, 55,
     "Local campaign, referral incentive and an agency framework to close the recruitment gap."),
    ("ACT-18", "Prepare a works council position paper with legal review", "own-10", 354, 352, "complete", "critical",
     ["rsk-20"], ["iss-11"], ["DEP-62"], 0.3, 100,
     "Legally reviewed position paper addressing the objection, plus a revised consultation calendar."),
    ("ACT-19", "Secure a written legacy TMS support extension to Q2", "own-14", 381, None, "in-progress", "high",
     ["rsk-21"], [], ["DEP-29"], 0.4, 40,
     "Extend legacy support to cover the revised two-wave go-live and hypercare period."),
    ("ACT-20", "Baseline and freeze the outstanding operational business rules", "own-05", 366, None, "overdue", "critical",
     ["rsk-22"], [], ["DEP-26"], 0.35, 50,
     "Formal baseline of the remaining rules with change control applied from the freeze date."),
    ("ACT-21", "Re-forecast programme cost with the approved change log", "own-11", 360, 358, "complete", "high",
     ["rsk-23"], [], [], 0.15, 100,
     "Bottom-up re-forecast including all approved changes and a revised contingency position."),
    ("ACT-22", "Establish a shared interface change calendar with Commerce Replatform", "own-02", 352, 350, "complete", "high",
     ["rsk-24"], [], ["DEP-66"], 0.35, 100,
     "Joint calendar and a standing collision review between the two programme change boards."),
    ("ACT-23", "Re-size hypercare for the two-wave go-live", "own-05", 386, None, "in-progress", "medium",
     ["rsk-25"], [], ["DEP-29"], 0.3, 70,
     "Revised hypercare rota, escalation model and vendor cover for the split go-live."),
    ("ACT-24", "Standardise carrier invoice formats to two accepted variants", "own-07", 384, None, "open", "medium",
     ["rsk-26"], [], ["DEP-40"], 0.3, 15,
     "Reduce six invoice formats to two so automated matching can be relied upon."),
    ("ACT-25", "Agree the benefit baseline for the five outstanding benefits", "own-11", 376, None, "in-progress", "critical",
     ["rsk-27"], [], ["DEP-65"], 0.35, 40,
     "Written finance agreement on baseline, measure and cadence for the benefits still unsigned."),
    ("ACT-26", "Complete threat models for the four remaining integration patterns", "own-13", 391, None, "in-progress", "high",
     ["rsk-28", "rsk-02"], [], ["DEP-35"], 0.25, 65,
     "Close the threat model gap so penetration testing is confirmatory rather than exploratory."),
    ("ACT-27", "Build a service level protection plan for the cutover window", "own-09", 382, None, "open", "high",
     ["rsk-29", "rsk-38"], [], ["DEP-63"], 0.3, 10,
     "Pre-agreed mitigations, customer communication and additional capacity for the cutover window."),
    ("ACT-28", "Model Frankfurt ramp-up with a slower learning curve", "own-04", 374, None, "in-progress", "medium",
     ["rsk-30"], [], [], 0.2, 45,
     "Sensitivity analysis on the ramp-up assumption and its effect on the benefit curve."),
    ("ACT-29", "Expedite the two outstanding racking aisles for Milan", "own-14", 348, 346, "complete", "high",
     ["rsk-31"], ["iss-09"], ["DEP-19"], 0.35, 100,
     "Expedited delivery of the short-shipped aisles to protect the fit-out completion date."),
    ("ACT-30", "Move a further 15% of linehaul volume onto fixed rates", "own-11", 390, None, "open", "medium",
     ["rsk-32"], [], [], 0.25, 5,
     "Third tender wave to reduce spot exposure on the highest volume lanes."),
    ("ACT-31", "Agree an availability ramp-up schedule in the automation contract", "own-08", 386, None, "open", "high",
     ["rsk-33"], [], ["DEP-49"], 0.3, 10,
     "Contractual availability ramp with remedies rather than a single day-one target."),
    ("ACT-32", "Increase masked production data volume in the test environment", "own-06", 364, None, "overdue", "high",
     ["rsk-34", "rsk-05"], ["iss-06"], [], 0.3, 35,
     "Raise test data volume from 4% to 40% of production so volume-sensitive defects surface before UAT exit."),
    ("ACT-33", "Submit the predictive ETA model for model risk review", "own-09", 378, None, "open", "medium",
     ["rsk-35"], [], ["DEP-56"], 0.35, 20,
     "Complete the model risk template and book the review slot before production deployment."),
    ("ACT-34", "Fund and appoint the run organisation roles", "own-01", 388, None, "open", "critical",
     ["rsk-41", "rsk-10", "rsk-36"], [], ["DEP-64"], 0.4, 15,
     "Business case addendum to fund the run roles so knowledge transfer has a receiving team."),
]
