"""ORION FMEA, DMAIC and metrics.

FMEA tuple: ref, process, step, failureMode, effect, cause, S, O, D,
existingControl, recommendedAction, owner, dueOffset, actionStatus,
postS, postO, postD, riskIds, causeRefs, controlRefs
"""

FMEA = [
    ("FM-01", "Carrier booking to invoice", "Receive booking request", "Booking message rejected by the carrier API",
     "Load is not tendered, operations revert to phone booking and premium rates apply",
     "Invoice and booking schema mismatch after the vendor specification gap",
     4, 4, 3, "Message validation with retry and a dead letter queue",
     "Build the in-house invoice adapter and add contract tests against each carrier schema", "own-06", 372, "in-progress",
     4, 2, 2, ["rsk-01", "rsk-03"], ["CSE-01"], ["CTL-02", "CTL-17"]),
    ("FM-02", "Carrier booking to invoice", "Confirm carrier acceptance", "Acceptance not received within the service window",
     "Load sits unconfirmed and misses the collection slot",
     "Carrier API certification incomplete for two carriers",
     4, 3, 2, "Unconfirmed booking exception report in the control tower",
     "Complete certification with the two outstanding carriers and add a fallback manual tender path", "own-07", 366, "in-progress",
     3, 2, 2, ["rsk-01", "rsk-03"], ["CSE-01"], ["CTL-01", "CTL-29"]),
    ("FM-03", "Carrier booking to invoice", "Transmit shipment data", "Address data rejected on cross-border loads",
     "Customs clearance delayed and the load is held at the border",
     "Character encoding defects in Italian and Polish address data",
     4, 4, 2, "Nightly data quality rules on the eight critical attributes",
     "Extend the encoding fix from the dry run to all legacy extracts and add pre-transmission validation", "own-12", 376, "in-progress",
     4, 2, 1, ["rsk-04", "rsk-14"], ["CSE-03"], ["CTL-05", "CTL-07"]),
    ("FM-04", "Carrier booking to invoice", "Track shipment events", "Tracking events not received from the carrier",
     "Control tower shows a blind shipment and the customer promise cannot be confirmed",
     "Carrier withheld data pending the liability clause",
     3, 4, 2, "Missing event alerting in the control tower",
     "Apply the fallback data sharing clause with the three holdout carriers", "own-07", 364, "in-progress",
     3, 2, 2, ["rsk-11", "rsk-10"], ["CSE-10"], ["CTL-15", "CTL-29"]),
    ("FM-05", "Carrier booking to invoice", "Submit customs declaration", "Declaration submitted with an incorrect commodity code",
     "Penalty, clearance delay and a customs correction entry",
     "Manual re-keying between the broker portal and the transport system",
     5, 3, 3, "Post-submission correction report reviewed weekly",
     "Automate the declaration handover through the broker interface or managed service", "own-07", 380, "open",
     5, 2, 2, ["rsk-14", "rsk-15"], ["CSE-11", "CSE-03"], ["CTL-16", "CTL-19"]),
    ("FM-06", "Carrier booking to invoice", "Receive carrier invoice", "Invoice cannot be matched to an executed load",
     "Invoice paid unmatched or held, causing rate leakage and disputed balances",
     "Six carrier invoice formats against a matcher designed for two",
     3, 5, 2, "Automated three-way match at cost, load and contract rate",
     "Standardise carrier invoice formats to two accepted variants", "own-07", 384, "open",
     3, 3, 2, ["rsk-26", "rsk-12"], ["CSE-19"], ["CTL-25"]),
    ("FM-07", "Carrier booking to invoice", "Post cost to the ledger", "Cost posted against the wrong hub or cost centre",
     "Reported freight cost per load is wrong and benefit measurement is unreliable",
     "Reporting definitions differ between operations and finance",
     4, 4, 3, "Monthly reconciliation of reporting to the general ledger",
     "Close the metric dictionary and align the cost centre mapping before the reporting gate", "own-11", 370, "in-progress",
     4, 2, 2, ["rsk-09", "rsk-27"], ["CSE-09"], ["CTL-13", "CTL-14"]),
    ("FM-08", "Carrier booking to invoice", "Publish the carrier scorecard", "Scorecard published from unreconciled data",
     "Carrier performance disputes and loss of credibility in commercial reviews",
     "Certified data set not available for reporting",
     3, 3, 3, "Data certification flag required before publication",
     "Gate scorecard publication on the reconciliation control passing", "own-09", 386, "open",
     3, 2, 2, ["rsk-09", "rsk-04"], ["CSE-02", "CSE-09"], ["CTL-05", "CTL-14"]),
    ("FM-09", "Carrier booking to invoice", "Authenticate the carrier connection", "Carrier credential compromised",
     "Unauthorised access to shipment and customer data across the connected estate",
     "Thirty-four carrier connections replace three regional gateways",
     5, 2, 3, "Continuous pipeline scanning and gateway rate limiting",
     "Complete threat models for the remaining integration patterns and enforce credential rotation", "own-13", 370, "in-progress",
     5, 1, 2, ["rsk-28", "rsk-02"], ["CSE-08"], ["CTL-03", "CTL-04", "CTL-16"]),

    ("FM-10", "Inbound to stock, automated hub", "Receive the inbound trailer", "Trailer arrives outside the booked slot",
     "Automation starves or queues and throughput drops below plan",
     "Slot compliance not enforced in the new booking flow",
     3, 4, 2, "Slot adherence exception report",
     "Enforce slot booking as a hard constraint in the carrier portal", "own-08", 388, "open",
     3, 2, 2, ["rsk-33", "rsk-19"], ["CSE-16"], ["CTL-29"]),
    ("FM-11", "Inbound to stock, automated hub", "Decant to totes", "Decant rate below the automation feed requirement",
     "Goods-to-person stations idle and the productivity benefit is not achieved",
     "Recruitment shortfall against the ramp-up curve",
     4, 4, 2, "Weekly recruitment pipeline tracking against the ramp curve",
     "Targeted recruitment campaign plus a temporary agency framework", "own-15", 358, "in-progress",
     4, 2, 2, ["rsk-19", "rsk-33"], ["CSE-14"], ["CTL-22"]),
    ("FM-12", "Inbound to stock, automated hub", "Automated putaway", "Shuttle fault stops an aisle",
     "Aisle inventory unavailable and order fulfilment is delayed",
     "Availability assumed at contractual level from day one",
     4, 3, 2, "Factory acceptance test with an availability warranty",
     "Agree a contractual availability ramp with remedies rather than a single day one target", "own-08", 386, "open",
     4, 2, 1, ["rsk-33", "rsk-08"], ["CSE-16"], ["CTL-11", "CTL-12"]),
    ("FM-13", "Inbound to stock, automated hub", "Goods-to-person pick", "Throughput below the contractual FAT figure",
     "Acceptance test fails, delaying both the payment milestone and go-live",
     "Throughput modelled on an annual average order profile",
     4, 4, 3, "Peak profile simulation before commissioning",
     "Re-run the simulation with three real peak weeks and re-derive the achievable figure", "own-08", 378, "in-progress",
     4, 3, 2, ["rsk-08", "rsk-33"], ["CSE-16"], ["CTL-11", "CTL-12"]),
    ("FM-14", "Inbound to stock, automated hub", "Interface stock update to the TMS", "Stock update not received by the transport system",
     "Loads are planned against stock that is not there, causing failed collections",
     "WMS to automation interface built late and tested at low volume",
     4, 3, 3, "Interface monitoring with reconciliation counts",
     "Increase masked production data volume in the test environment to 40%", "own-06", 364, "in-progress",
     4, 2, 2, ["rsk-34", "rsk-05"], ["CSE-06"], ["CTL-07", "CTL-17"]),
    ("FM-15", "Inbound to stock, automated hub", "Power the automation system", "Automation loses power during operation",
     "Full hub stoppage with recovery measured in hours",
     "Utility upgrade not energised, temporary supply in use",
     5, 2, 2, "Permit and utility lead time tracker with escalation",
     "Confirm the generator bridge specification and test a controlled failover", "own-04", 366, "in-progress",
     5, 1, 2, ["rsk-07"], ["CSE-05"], ["CTL-10"]),
    ("FM-16", "Inbound to stock, automated hub", "Commission the system", "Commissioning engineers not available",
     "Factory acceptance test slips, moving warehouse go-live and the network cutover",
     "Supplier reallocated capacity to another customer",
     5, 4, 2, "Weekly vendor delivery review with contractual escalation",
     "Negotiate a protected build slot with liquidated damages for further movement", "own-14", 360, "in-progress",
     5, 3, 2, ["rsk-06"], ["CSE-04"], ["CTL-01", "CTL-08", "CTL-09"]),
    ("FM-17", "Inbound to stock, automated hub", "Operate under the new process", "Operators revert to the legacy process",
     "Automation bypassed, so productivity and claims benefits are not realised",
     "Super-user certification behind target and change fatigue",
     3, 4, 3, "Named tester and trainee allocation confirmed in writing",
     "Add programme contribution to hub manager scorecards and re-plan the training calendar", "own-15", 356, "in-progress",
     3, 3, 2, ["rsk-17", "rsk-36"], ["CSE-07", "CSE-13"], ["CTL-18", "CTL-21"]),
    ("FM-18", "Inbound to stock, automated hub", "Hand over to the run organisation", "No named receiving owner for an artefact",
     "Knowledge is lost at handover and defects resurface with nobody accountable",
     "Run organisation roles not funded until the next budget cycle",
     4, 4, 3, "Knowledge transfer plan with run organisation acceptance",
     "Fund and appoint the run organisation roles before the handover gate", "own-01", 388, "open",
     4, 2, 2, ["rsk-41", "rsk-10"], ["CSE-21"], ["CTL-32", "CTL-20"]),
]


DMAIC = [
    {
        "id": "dmc-01",
        "ref": "DM-01",
        "name": "Reduce master data defect rate to the migration exit threshold",
        "ownerId": "own-12",
        "phase": "improve",
        "start": 288,
        "target": 400,
        "define": {
            "problemStatement": "The defect rate on the eight critical master data attributes is 3.4% against a migration exit threshold of 1.5%. Defects are arriving faster than the remediation team can clear them, which has moved the data quality exit date twice and now threatens the reporting gate and benefit measurement.",
            "businessImpact": "Blocks the reporting suite acceptance, delays benefit baselining and creates rework in every downstream load. Modelled cost of poor quality is 246,000 for the programme period.",
            "customerImpact": "Address and weight defects cause failed collections and border holds, which are visible to the end customer as missed delivery promises.",
            "ctq": [
                "Defect rate on critical attributes at or below 1.5% at the exit gate",
                "No critical attribute without a named accountable owner",
                "Clearance rate at or above the arrival rate for four consecutive weeks",
            ],
            "inScope": [
                "The eight critical attributes used by transport planning, customs and invoicing",
                "All three regional legacy source systems",
                "The staging layer remediation process",
            ],
            "outOfScope": [
                "Non-critical descriptive attributes",
                "Historic records outside the eighteen month migration window",
                "Customer master data, owned by the commercial programme",
            ],
            "goalStatement": "Reduce the critical attribute defect rate from 3.4% to 1.5% or below by the migration exit gate, and hold clearance at or above arrival for four consecutive weeks.",
        },
        "measure": {
            "metricName": "Critical attribute defect rate",
            "unit": "percent of records",
            "baseline": 3.4,
            "volume": 1_840_000,
            "defectRate": 0.034,
            "cycleTimeDays": 11.5,
            "costOfPoorQuality": 246_000,
            "dataSource": "Nightly data quality rule engine, eight critical attributes",
            "trend": [(288, 2.9), (302, 3.0), (316, 3.1), (330, 3.3), (344, 3.4), (358, 3.5), (371, 3.4)],
        },
        "analyze": {
            "causeIds": ["CSE-02", "CSE-03", "CSE-06"],
            "fmeaIds": ["FM-03", "FM-07", "FM-08"],
            "hypothesis": "Defect arrival is driven by manual re-keying at the hubs and by the absence of attribute-level ownership, not by the remediation process itself.",
            "finding": "Confirmed. Pareto shows two causes account for 78% of defect volume: no single owner for master data quality across regions, and manual re-keying between legacy systems. The staging layer approach chosen in DEC-08 clears defects but does not stop them arriving.",
        },
        "improve": [
            ("Assign named owners to all eight critical attributes", 0.35, "own-12", "Two attributes as a pilot in period 11", 366, "piloting"),
            ("Add three data quality contractors to clear the backlog", 0.2, "own-12", "Full scope, approved as CHG-13", 344, "implemented"),
            ("Automate the two highest volume re-keying steps at the hubs", 0.3, "own-06", "Milan hub only", 382, "planned"),
            ("Add encoding validation before transmission", 0.15, "own-12", "Italian and Polish address data", 376, "piloting"),
        ],
        "control": {
            "controlMetric": "Weekly critical attribute defect rate",
            "ucl": 1.5,
            "lcl": 0.0,
            "frequency": "weekly",
            "escalationTrigger": "Two consecutive weeks above 1.5% or any week where arrival exceeds clearance by more than 10%",
            "ownerId": "own-12",
            "linkedControlIds": ["CTL-05", "CTL-06", "CTL-07"],
        },
        "riskIds": ["rsk-04", "rsk-09", "rsk-34"],
    },
    {
        "id": "dmc-02",
        "ref": "DM-02",
        "name": "Reduce premium and expedited freight as a share of spend",
        "ownerId": "own-05",
        "phase": "analyze",
        "start": 318,
        "target": 420,
        "define": {
            "problemStatement": "Premium and expedited freight is running at 8.3% of transport spend against a target of 4.1%. Every booking failure, missed slot or late customs clearance converts a planned movement into a premium one, and the benefit case for BEN-04 assumes the reduction happens at go-live.",
            "businessImpact": "The gap between 8.3% and 4.1% is worth 1.2M annually, which is the entire BEN-04 benefit. Modelled cost of poor quality for the programme period is 318,000.",
            "customerImpact": "Premium freight usually follows a service failure, so the customer has already experienced a missed promise before the cost is incurred.",
            "ctq": [
                "Premium freight at or below 4.1% of transport spend",
                "Booking failure rate below 0.5% of tendered loads",
                "Customs hold rate below 1% of cross-border loads",
            ],
            "inScope": [
                "All European road freight movements in the wave 1 network",
                "Booking, tender and customs handover process steps",
            ],
            "outOfScope": [
                "Air and sea freight",
                "Customer-requested expedites, which are recharged",
            ],
            "goalStatement": "Reduce premium freight from 8.3% to 4.1% of spend within four months of wave 1 cutover by removing the booking and customs failure modes that cause it.",
        },
        "measure": {
            "metricName": "Premium freight share of transport spend",
            "unit": "percent of spend",
            "baseline": 8.3,
            "volume": 214_000,
            "defectRate": 0.083,
            "cycleTimeDays": 2.1,
            "costOfPoorQuality": 318_000,
            "dataSource": "Transport spend analysis, premium service codes",
            "trend": [(318, 9.4), (332, 9.1), (346, 8.8), (360, 8.5), (371, 8.3)],
        },
        "analyze": {
            "causeIds": ["CSE-01", "CSE-11", "CSE-19"],
            "fmeaIds": ["FM-01", "FM-02", "FM-05"],
            "hypothesis": "Premium freight is concentrated in loads where the booking failed or customs held the load, rather than being spread evenly across lanes.",
            "finding": "In progress. Early analysis attributes 61% of premium spend to two failure modes: booking message rejection and customs commodity code corrections. Both are already on the FMEA with actions open.",
        },
        "improve": [
            ("Build the in-house invoice adapter to remove booking rejections", 0.4, "own-06", "Two tier 1 carriers first", 372, "piloting"),
            ("Automate the customs declaration handover", 0.25, "own-07", "Cross-border consolidated loads", 380, "planned"),
            ("Enforce slot booking as a hard constraint", 0.12, "own-08", "Milan hub", 388, "planned"),
        ],
        "control": {
            "controlMetric": "Monthly premium freight share of spend",
            "ucl": 4.1,
            "lcl": 0.0,
            "frequency": "monthly",
            "escalationTrigger": "Any month above 5% after wave 1 cutover, or any week with more than 20 booking rejections",
            "ownerId": "own-05",
            "linkedControlIds": ["CTL-02", "CTL-17", "CTL-25"],
        },
        "riskIds": ["rsk-01", "rsk-03", "rsk-14"],
    },
]


# id, name, unit, workstream, target, direction, series of (offset, value)
METRICS = [
    ("met-01", "Critical attribute defect rate", "percent", "ws-int", 1.5, "lower-is-better",
     [(288, 2.9), (302, 3.0), (316, 3.1), (330, 3.3), (344, 3.4), (358, 3.5), (371, 3.4)]),
    ("met-02", "Open severity 2 UAT defects", "defects", "ws-tms", 22, "lower-is-better",
     [(300, 12), (314, 19), (328, 31), (342, 38), (356, 44), (371, 47)]),
    ("met-03", "Premium freight share of spend", "percent", "ws-tms", 4.1, "lower-is-better",
     [(318, 9.4), (332, 9.1), (346, 8.8), (360, 8.5), (371, 8.3)]),
    ("met-04", "On-time in-full delivery performance", "percent", "ws-ctl", 97.2, "higher-is-better",
     [(300, 91.2), (320, 91.4), (340, 91.6), (358, 91.9), (371, 91.8)]),
    ("met-05", "Super-users certified", "people", "ws-chg", 90, "higher-is-better",
     [(320, 8), (334, 22), (348, 38), (362, 49), (371, 55)]),
    ("met-06", "Freight cost per consolidated load", "EUR", "ws-net", 318, "lower-is-better",
     [(240, 409), (270, 401), (300, 392), (330, 383), (360, 374), (371, 371)]),
]
